
months_threshold = 6 

# 0-Low Risk 1-High Risk
"""
low_risk_sectors = [
    'Medical Practices (GPs, Clinics, Dentists)',
    'Pharmacies (Independent or Small Chains)',
    'Accounting and Tax Preparation Firms',
    'IT Services and Support Companies',
    'Courier Services (Independent and Regional Operators)',
    'Grocery Stores and Mini-Markets',
    'Residential Real Estate Agencies',
    'Education',
    'Engineering',
    'Estate Agent',
    'Food Service',
    'Import / Export',
    'Manufacturing',
    'Marketing / Advertising / Design',
    'Off-Licence Business',
    'Telecommunications',
    'Tradesman',
    'Wholesaler / Distributor'
]

high_risk_sectors = [
    'Other',
    'Restaurants and Cafes',
    'Bars and Pubs',
    'Beauty Salons and Spas',
    'E-Commerce Retailers',
    'Personal Services',
    'Event Planning and Management Firms',
    'Auto Repair Shops',
    'Fitness Centres and Gyms',
    'Residential Construction Firms',
    'Printing / Publishing',
    'Recruitment',
    'Retail',
    
]
"""

# Define industry-specific thresholds
industry_thresholds = dict(sorted({
    'Medical Practices (GPs, Clinics, Dentists)': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 0,
        'Operating Margin': 0.08,
        'Expense-to-Revenue Ratio': 1.05,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 18000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Pharmacies (Independent or Small Chains)': {
        'Debt Service Coverage Ratio': 1.45,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.06,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.09,
        'Gross Burn Rate': 16000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Accounting and Tax Preparation Firms': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 0,
        'Operating Margin': 0.07,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 15000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'IT Services and Support Companies': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 0,
        'Operating Margin': 0.10,
        'Expense-to-Revenue Ratio': 1.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 14000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Courier Services (Independent and Regional Operators)': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.13,
        'Gross Burn Rate': 13000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 300,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Grocery Stores and Mini-Markets': {
        'Debt Service Coverage Ratio': 1.25,
        'Net Income': 0,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.15,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 11000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Residential Real Estate Agencies': {
        'Debt Service Coverage Ratio': 1.35,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 12000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Education': {
        'Debt Service Coverage Ratio': 1.31,
        'Net Income': 126,
        'Operating Margin': 0.08,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 12277,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 437,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Engineering': {
        'Debt Service Coverage Ratio': 1.42,
        'Net Income': 6213,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.13,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 14573,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 401,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Estate Agent': {
        'Debt Service Coverage Ratio': 1.31,
        'Net Income': 3872,
        'Operating Margin': 0.08,
        'Expense-to-Revenue Ratio': 1.16,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 14415,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 445,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Food Service': {
        'Debt Service Coverage Ratio': 1.41,
        'Net Income': 2191,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.17,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 10334,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 466,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Import / Export': {
        'Debt Service Coverage Ratio': 1.38,
        'Net Income': 2464,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.20,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.19,
        'Gross Burn Rate': 9625,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 540,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Manufacturing': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 1114,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 14557,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 469,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Marketing / Advertising / Design': {
        'Debt Service Coverage Ratio': 1.39,
        'Net Income': 4425,
        'Operating Margin': 0.09,
        'Expense-to-Revenue Ratio': 1.14,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 14081,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 543,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Off-Licence Business': {
        'Debt Service Coverage Ratio': 1.41,
        'Net Income': 4092,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.13,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.13,
        'Gross Burn Rate': 15611,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 403,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Other': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 2500,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.15,
        'Gross Burn Rate': 12000,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 450,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Personal Services': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 1482,
        'Operating Margin': 0.07,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 13381,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 476,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Restaurants and Cafes': {
        'Debt Service Coverage Ratio': 1.10,
        'Net Income': -1000,
        'Operating Margin': 0.03,
        'Expense-to-Revenue Ratio': 1.20,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.20,
        'Gross Burn Rate': 10000,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 350,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Bars and Pubs': {
        'Debt Service Coverage Ratio': 1.05,
        'Net Income': -2000,
        'Operating Margin': 0.02,
        'Expense-to-Revenue Ratio': 1.25,
        'Revenue Growth Rate': 0.01,
        'Cash Flow Volatility': 0.22,
        'Gross Burn Rate': 9500,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 350,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Beauty Salons and Spas': {
        'Debt Service Coverage Ratio': 1.15,
        'Net Income': 0,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 8000,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 300,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'E-Commerce Retailers': {
        'Debt Service Coverage Ratio': 1.20,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.15,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.17,
        'Gross Burn Rate': 11000,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Event Planning and Management Firms': {
        'Debt Service Coverage Ratio': 1.10,
        'Net Income': -500,
        'Operating Margin': 0.03,
        'Expense-to-Revenue Ratio': 1.22,
        'Revenue Growth Rate': 0.01,
        'Cash Flow Volatility': 0.19,
        'Gross Burn Rate': 9000,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 3,
        'Number of Bounced Payments': 0,
    },
    'Auto Repair Shops': {
        'Debt Service Coverage Ratio': 1.25,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.15,
        'Gross Burn Rate': 10500,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Fitness Centres and Gyms': {
        'Debt Service Coverage Ratio': 1.20,
        'Net Income': -1000,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.21,
        'Gross Burn Rate': 9500,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 400,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Residential Construction Firms': {
        'Debt Service Coverage Ratio': 1.15,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.17,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.20,
        'Gross Burn Rate': 11500,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Printing / Publishing': {
        'Debt Service Coverage Ratio': 1.47,
        'Net Income': 1979,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 10226,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 460,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Recruitment': {
        'Debt Service Coverage Ratio': 1.37,
        'Net Income': 1094,
        'Operating Margin': 0.07,
        'Expense-to-Revenue Ratio': 1.15,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 11894,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 474,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Retail': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 1858,
        'Operating Margin': 0.08,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.17,
        'Gross Burn Rate': 10798,
        'Directors Score': 65,
        'Sector Risk': 1,
        'Average Month-End Balance': 473,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Telecommunications': {
        'Debt Service Coverage Ratio': 1.45,
        'Net Income': 4229,
        'Operating Margin': 0.09,
        'Expense-to-Revenue Ratio': 1.19,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.17,
        'Gross Burn Rate': 12315,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 516,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Tradesman': {
        'Debt Service Coverage Ratio': 1.26,
        'Net Income': 3484,
        'Operating Margin': 0.07,
        'Expense-to-Revenue Ratio': 1.17,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.20,
        'Gross Burn Rate': 10528,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 599,
        'Average Negative Balance Days per Month': 4,
        'Number of Bounced Payments': 0,
    },
    'Wholesaler / Distributor': {
        'Debt Service Coverage Ratio': 1.42,
        'Net Income': 2935,
        'Operating Margin': 0.09,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.16,
        'Gross Burn Rate': 12634,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 411,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },

}.items()))

weights = {
    'Debt Service Coverage Ratio': 18,  
    'Net Income': 12,                   
    'Operating Margin': 8,             
    'Expense-to-Revenue Ratio': 7,     
    'Revenue Growth Rate': 5,           
    'Cash Flow Volatility': 11,          
    'Gross Burn Rate': 3,               
    'Months': 4,                       
    'Directors Score': 17,
    'Sector Risk': 3,
    'Average Month-End Balance': 5,
    'Average Negative Balance Days per Month': 6,
    'Number of Bounced Payments': 1,
}

def calculate_risk(requested_loan, monthly_average_revenue):
    if requested_loan <= 0.7 * monthly_average_revenue:
        return 'Low Risk', f"Requested loan amount of {requested_loan} is less than or equal to 70% of the average monthly revenue ({monthly_average_revenue}), classified as Low Risk."
    elif 0.7 * monthly_average_revenue < requested_loan <= monthly_average_revenue:
        return 'Moderate Low Risk', f"Requested loan amount of {requested_loan} is between 70% and 100% of the average monthly revenue ({monthly_average_revenue}), classified as Moderate Low Risk."
    elif monthly_average_revenue < requested_loan <= 1.2 * monthly_average_revenue:
        return 'Medium Risk', f"Requested loan amount of {requested_loan} is between 100% and 120% of the average monthly revenue ({monthly_average_revenue}), classified as Medium Risk."
    elif 1.2 * monthly_average_revenue < requested_loan <= 1.5 * monthly_average_revenue:
        return 'Moderate High Risk', f"Requested loan amount of {requested_loan} is between 120% and 150% of the average monthly revenue ({monthly_average_revenue}), classified as Moderate High Risk."
    else:
        return 'High Risk', f"Requested loan amount of {requested_loan} is greater than 150% of the average monthly revenue ({monthly_average_revenue}), classified as High Risk."
