
months_threshold = 6 

# 0-Low Risk 1-High Risk
"""
low_risk_sectors = [
    'Healthcare and Pharmaceuticals',
    'Professional Services',
    'Consumer Staples',
    'Information Technology and Software',
    'Transportation and Logistics',
    'Real Estate Services',
    'Environmental Services'
]

high_risk_sectors = [
    'Hospitality and Food',
    'Entertainment and Leisure',
    'Retail',
    'Construction and Trades',
    'Automotive Services',
    'Personal Services',
    'Event Management'
]
"""

# Define industry-specific thresholds
industry_thresholds = dict(sorted({
    'Medical Practices (GPs, Clinics, Dentists)': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 0,
        'Operating Margin': 0.08,
        'Expense-to-Revenue Ratio': 1.05,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 18000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Pharmacies (Independent or Small Chains)': {
        'Debt Service Coverage Ratio': 1.45,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.06,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.09,
        'Gross Burn Rate': 16000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Allied Health Services': {
        'Debt Service Coverage Ratio': 1.35,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.07,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 12000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Accounting and Tax Preparation Firms': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 0,
        'Operating Margin': 0.07,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 15000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'IT Services and Support Companies': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 0,
        'Operating Margin': 0.10,
        'Expense-to-Revenue Ratio': 1.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 14000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Courier Services (Independent and Regional Operators)': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.13,
        'Gross Burn Rate': 13000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Grocery Stores and Mini-Markets': {
        'Debt Service Coverage Ratio': 1.25,
        'Net Income': 0,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.15,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 11000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Residential Real Estate Agencies': {
        'Debt Service Coverage Ratio': 1.35,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.10,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 12000,
        'Directors Score': 65,
        'Sector Risk': 0,
        'Average Month-End Balance': 500,
    },
    'Restaurants and Cafes': {
        'Debt Service Coverage Ratio': 1.10,
        'Net Income': -1000,
        'Operating Margin': 0.03,
        'Expense-to-Revenue Ratio': 1.20,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.20,
        'Gross Burn Rate': 10000,
        'Directors Score': 60,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Bars and Pubs': {
        'Debt Service Coverage Ratio': 1.05,
        'Net Income': -2000,
        'Operating Margin': 0.02,
        'Expense-to-Revenue Ratio': 1.25,
        'Revenue Growth Rate': 0.01,
        'Cash Flow Volatility': 0.22,
        'Gross Burn Rate': 9500,
        'Directors Score': 58,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Beauty Salons and Spas': {
        'Debt Service Coverage Ratio': 1.15,
        'Net Income': 0,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 8000,
        'Directors Score': 60,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'E-Commerce Retailers': {
        'Debt Service Coverage Ratio': 1.20,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Expense-to-Revenue Ratio': 1.15,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.17,
        'Gross Burn Rate': 11000,
        'Directors Score': 62,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Event Planning and Management Firms': {
        'Debt Service Coverage Ratio': 1.10,
        'Net Income': -500,
        'Operating Margin': 0.03,
        'Expense-to-Revenue Ratio': 1.22,
        'Revenue Growth Rate': 0.01,
        'Cash Flow Volatility': 0.19,
        'Gross Burn Rate': 9000,
        'Directors Score': 60,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Auto Repair Shops': {
        'Debt Service Coverage Ratio': 1.25,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.12,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.15,
        'Gross Burn Rate': 10500,
        'Directors Score': 61,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Fitness Centres and Gyms': {
        'Debt Service Coverage Ratio': 1.20,
        'Net Income': -1000,
        'Operating Margin': 0.04,
        'Expense-to-Revenue Ratio': 1.18,
        'Revenue Growth Rate': 0.02,
        'Cash Flow Volatility': 0.21,
        'Gross Burn Rate': 9500,
        'Directors Score': 60,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
    'Residential Construction Firms': {
        'Debt Service Coverage Ratio': 1.15,
        'Net Income': 0,
        'Operating Margin': 0.06,
        'Expense-to-Revenue Ratio': 1.17,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.20,
        'Gross Burn Rate': 11500,
        'Directors Score': 60,
        'Sector Risk': 1,
        'Average Month-End Balance': 500,
    },
}.items()))

weights = {
    'Debt Service Coverage Ratio': 17,  
    'Net Income': 14,                   
    'Operating Margin': 9,             
    'Expense-to-Revenue Ratio': 8,     
    'Revenue Growth Rate': 5,           
    'Cash Flow Volatility': 11,          
    'Gross Burn Rate': 3,               
    'Months': 5,                       
    'Directors Score': 15,
    'Sector Risk': 8,
    'Average Month-End Balance': 5,
}

def calculate_risk(requested_loan, monthly_average_revenue):
    if requested_loan <= 0.7 * monthly_average_revenue:
        return 'Low Risk', f"Requested loan amount of {requested_loan} is less than or equal to 70% of the average monthly revenue ({monthly_average_revenue}), classified as Low Risk."
    elif 0.7 * monthly_average_revenue < requested_loan <= monthly_average_revenue:
        return 'Moderate Low Risk', f"Requested loan amount of {requested_loan} is between 70% and 100% of the average monthly revenue ({monthly_average_revenue}), classified as Moderate Low Risk."
    elif monthly_average_revenue < requested_loan <= 1.2 * monthly_average_revenue:
        return 'Medium Risk', f"Requested loan amount of {requested_loan} is between 100% and 120% of the average monthly revenue ({monthly_average_revenue}), classified as Medium Risk."
    elif 1.2 * monthly_average_revenue < requested_loan <= 1.5 * monthly_average_revenue:
        return 'Moderate High Risk', f"Requested loan amount of {requested_loan} is between 120% and 150% of the average monthly revenue ({monthly_average_revenue}), classified as Moderate High Risk."
    else:
        return 'High Risk', f"Requested loan amount of {requested_loan} is greater than 150% of the average monthly revenue ({monthly_average_revenue}), classified as High Risk."
